= Lab Environment Customization

Hopefully you have already requested your lab environment and have been enjoying the reference material provdied before getting started in the lab.

If you have reached this point and did not request your lab environment.

[OPTION 1]

Not to worry, this course includes interactive experiences that provide a visual representation of using the product to perform AI model inference and more. 

[OPTION 2]

Go here to deploy the lab environment,it takes around 1.5 on average, sometimes a bit more, but the system will email you when its ready. 

---

== Arcade Interactive Experience:  Logging into OpenShift and Upgrading Open Shift AI

In our lab environment OpenShift AI is already installed, however the version installled vis 4.18 which has an older version of the vLLM runtime. So before we get started, I suggest you also update your environment to OpenShift AI v2.21 or later which includes vLLM v.9.01 which is closer to the latest version 0.9.1.  (as of 07042025)

---

++++
<iframe 
  src="https://demo.arcade.software/upbkf0tsF1xerzXGmWsC?embed&embed_mobile=inline&embed_desktop=inline&show_copy_link=true"
  width="100%" 
  height="600px" 
  frameborder="0" 
  allowfullscreen
  webkitallowfullscreen
  mozallowfullscreen
  allow="clipboard-write"
  muted>
</iframe>
++++
